pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'com.android.library') {
                useModule('com.android.tools.build:gradle:8.13.2')
            } else if (requested.id.id == 'org.jetbrains.kotlin.android') {
                useModule('org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.10')
            }
        }
    }
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "AtlasMediaWidget"
include ':app', ':api-app', ':media-core', ':vendor-oneos', ':vendor-ecarx-stub', ':media-runtime'
